version: "3.9"

services:

  mysql:

    image: mysql:8

    container_name: collabify_mysql

    restart: always

    environment:

      MYSQL_ROOT_PASSWORD: root

      MYSQL_DATABASE: collabify

    ports:

      - "3307:3306"

    volumes:

      - mysql_data:/var/lib/mysql

  backend:

    build: ./backend_Gl

    container_name: collabify_backend

    restart: always

    ports:

      - "8081:8081"

    depends_on:

      - mysql

  frontend:

    build: ./frontend_Gl

    container_name: collabify_frontend

    restart: always

    ports:

      - "5173:5173"

    depends_on:

      - backend

volumes:

  mysql_data: